services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf:/etc/nginx/templates
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80
      - APP_PORT=3000
  app:
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    command: ["node", "/app/app.js"]